export type SolutionDoc = {
	file: string;
	date: string | null;
	title: string;
};

/**
 * The real docs/solutions/ corpus from the shinobu repo, snapshotted
 * 2026-08-13. One file per solved bug or non-obvious pattern; the H1 is a
 * claim, not a topic.
 */
export const solutionsCorpus: SolutionDoc[] = [
	{ file: "android-ci-tag-cache-scoping.md", date: "2026-07-26", title: "Tag-triggered release builds are always cold: Actions caches are ref-scoped" },
	{ file: "android-pressable-over-textinput.md", date: "2026-07-26", title: "Android: a pressable positioned on top of a TextInput never fires" },
	{ file: "anilist-custom-lists-untyped-json.md", date: "2026-07-29", title: "AniList MediaList.customLists is an untyped Json map of every list" },
	{ file: "anilist-rate-limit-retry-storm.md", date: null, title: "AniList 429s from ordinary browsing: staleTime 0 + default retries = rate-limit storm" },
	{ file: "anilist-shared-list-query-status-gate.md", date: "2026-07-28", title: "Widening the AniList list read: one query, two consumers, and the status the normalizer ate" },
	{ file: "anilist-web-prod-redirects-to-localhost.md", date: "2026-08-03", title: "AniList connect on production web redirected to localhost:8081" },
	{ file: "anizip-misses-anime-films-by-tmdb-id.md", date: "2026-07-25", title: "ani.zip's TMDB index is TV-oriented — anime films reverse-map to nothing" },
	{ file: "anizip-tvdb-seasons-vs-tracker-seasons.md", date: "2026-07-27", title: "ani.zip's seasons are TVDB's, and the trackers' usually aren't" },
	{ file: "better-all-result-keys-completion-order.md", date: null, title: "better-all result keys are in completion order, not input order" },
	{ file: "bottom-sheet-content-detent-clips-tall-content.md", date: "2026-07-26", title: "A tall bottom sheet clips its content instead of scrolling" },
	{ file: "bun-mock-module-leaks-across-suites.md", date: "2026-07-23", title: "mock.module leaks into other test files (and mock.restore() doesn't undo it)" },
	{ file: "bun-test-mock-module-cross-file-leak.md", date: null, title: "mock.module on a shared module leaks across test files — --isolate is required" },
	{ file: "bun-test-module-memo-leaks-across-files.md", date: "2026-07-27", title: "A faked window in one test file hands a TMDB token to every later one" },
	{ file: "burnt-toast-platform-behaviour.md", date: "2026-08-03", title: "burnt toast: what it actually rendered per platform — and why it was replaced" },
	{ file: "button-classname-padding-shrinks-the-label.md", date: "2026-07-27", title: "Padding passed to Button through className shrinks the label instead of widening the button" },
	{ file: "cloudflare-workers-static-web-deploy.md", date: "2026-07-20", title: "Web deploys via Cloudflare Workers static assets, not EAS Hosting" },
	{ file: "double-tap-pushes-two-detail-screens.md", date: null, title: "A double tap pushes two detail screens" },
	{ file: "expo-dev-client-vs-expo-go.md", date: "2026-07-04", title: "bun ios/bun android opened Expo Go and failed with HTTP 500" },
	{ file: "expo-notifications-foreground-handler.md", date: "2026-07-24", title: "expo-notifications: no handler means no banner while the app is open" },
	{ file: "expo-router-head-ios-handoff.md", date: null, title: "expo-router/head throws on iOS unless Handoff origin is configured" },
	{ file: "expo-stale-session-unexpected-server-data.md", date: null, title: "Dev client failed to load: UnexpectedServerData: No returned query result" },
	{ file: "expo-web-ssr-mmkv-storage-on-server.md", date: null, title: "Expo Web SSR: MMKV storage accessed during server render" },
	{ file: "galeria-web-zoom-morph-giant-circle.md", date: null, title: "galeria's web zoom morph balloons into a giant circle" },
	{ file: "hermes-no-es2023-array-methods.md", date: null, title: "Hermes doesn't implement ES2023 change-by-copy array methods" },
	{ file: "legend-list-horizontal-content-padding-web.md", date: "2026-07-25", title: "Horizontal Legend List rows lose their leading padding on web" },
	{ file: "letterboxd-diary-html-cloudflare-walled.md", date: "2026-07-21", title: "Letterboxd diary: RSS works, deep-history HTML pages are Cloudflare-walled" },
	{ file: "letterboxd-no-api-fallback.md", date: "2026-07-15", title: "Letterboxd without the official API: what works and what doesn't" },
	{ file: "letterboxd-tags-page-scrapeable.md", date: "2026-07-25", title: "Letterboxd tag index: /{user}/tags/ is scrapeable (200, not Cloudflare-walled)" },
	{ file: "letterboxd-watchlist-release-resolve-cost.md", date: "2026-07-27", title: "Letterboxd watchlist → release dates: what the resolve actually costs" },
	{ file: "letterboxd-watchlist-write.md", date: "2026-07-29", title: "Letterboxd: the watchlist endpoint, as observed" },
	{ file: "letterboxd-web-proxy.md", date: "2026-07-20", title: "Letterboxd web proxy spike: server-side reads work, writes are Cloudflare-walled" },
	{ file: "local-web-dev-proxy-middleware.md", date: "2026-07-22", title: "Local web dev: /api/* proxies 404 on Metro (and masquerade as \"username not found\")" },
	{ file: "mixed-date-only-and-instant-ordering.md", date: "2026-07-25", title: "Sorting a list that mixes bare dates and ISO instants" },
	{ file: "nitro-connection-warmup.md", date: null, title: "Warming provider connections ahead of the Up Next waterfall" },
	{ file: "persisted-query-cache-set-and-map-corruption.md", date: "2026-07-28", title: "Persisting the query cache: Set and Map payloads corrupt silently" },
	{ file: "platform-split-no-bare-index-breaks-typecheck.md", date: null, title: "A platform-split pair with no bare index.ts fails tsc, even though Metro resolves it fine" },
	{ file: "pod-install-stale-podfile-lock.md", date: null, title: "bun ios failed at pod install after adding an Expo package" },
	{ file: "prebuild-xmldom-mimetype-stale-node-modules.md", date: null, title: "Prebuild fails: DOMParser.parseFromString \"undefined\" mimeType" },
	{ file: "pressto-accessibility-state-not-mapped-on-web.md", date: "2026-07-26", title: "A pressto pressable's disabled/accessibilityState never reaches the DOM" },
	{ file: "pressto-border-not-drawn-on-android.md", date: "2026-07-26", title: "A border on a pressto pressable is invisible on Android" },
	{ file: "quick-log-settle-refresh-to-update.md", date: "2026-08-02", title: "Quick-log \"Logged — refresh to update\" (stranded settle)" },
	{ file: "react-error-boundaries.md", date: null, title: "React Error Boundaries" },
	{ file: "reanimated-web-keyframe-pins-position.md", date: "2026-07-27", title: "A custom Keyframe entering animation pins the element to position: absolute on web" },
	{ file: "reserve-the-row-a-late-control-will-need.md", date: "2026-07-27", title: "A control that can only appear after a measurement must reserve its row up front" },
	{ file: "season-drop-batching.md", date: null, title: "Collapsing a same-day season drop into one card and one notification" },
	{ file: "serializd-watchlist-clears-watched.md", date: "2026-07-30", title: "Serializd: does a watchlist write clear watched state?" },
	{ file: "serializd-watchlist-endpoints.md", date: "2026-07-28", title: "Serializd watchlist endpoints — how they were found, and how to re-find them" },
	{ file: "sheet-scroller-swap-render-loop.md", date: "2026-07-26", title: "A sheet that measures its children to decide how to wrap them loops forever" },
	{ file: "simkl-completed-shows-have-no-episode-detail.md", date: "2026-08-01", title: "A fully-watched Simkl show reads as unwatched" },
	{ file: "simkl-only-tv-details-trakt-gated.md", date: "2026-08-01", title: "Simkl-only TV details: no log button, no seasons (Trakt-gated surfaces)" },
	{ file: "simkl-parked-shows-have-no-next-to-watch.md", date: "2026-08-01", title: "A Simkl show parked outside watching went dark on its own details screen" },
	{ file: "simkl-parked-shows-miss-continue-watching.md", date: "2026-08-01", title: "A part-watched Simkl show parked on the watchlist never reached Continue Watching" },
	{ file: "simkl-rate-limits-and-write-lock.md", date: "2026-07-31", title: "Simkl rate limits, the 20-second write lock, and batching discipline" },
	{ file: "simkl-watched-movies-never-read-back.md", date: "2026-08-01", title: "A movie watched on Simkl still offered \"Mark as watched\"" },
	{ file: "simkl-watchlist-remove-deletes-history.md", date: "2026-08-01", title: "Simkl's only un-track deletes watch history, so the removal reads first" },
	{ file: "trakt-oauth-setup.md", date: null, title: "Trakt OAuth Setup" },
	{ file: "trakt-progress-episodes-have-no-season-field.md", date: null, title: "Trakt progress episodes have no season field" },
	{ file: "trakt-streaming-calendar-path.md", date: "2026-07-27", title: "Trakt's digital-release calendar is streaming, not digital" },
	{ file: "trakt-text-search-wrong-movie-match.md", date: "2026-07-17", title: "Trakt title search resolves to the wrong film without a year gate" },
	{ file: "trakt-transient-network-errors.md", date: null, title: "Intermittent trakt: network error — NetworkError when attempting to fetch resource" },
	{ file: "trakt-watched-endpoints-2026-api-changes.md", date: null, title: "Trakt watched endpoints: 2026 breaking changes (images gone, pagination required)" },
	{ file: "trakt-watchlist-pagination-2026.md", date: "2026-06-15", title: "Trakt /sync/watchlist: pagination is required, and the blueprint says otherwise" },
	{ file: "unicode-diacritic-property-eats-middle-dot.md", date: null, title: "\\p{Diacritic} silently eats U+00B7 MIDDLE DOT when slugifying names" },
	{ file: "uniwind-classname-third-party-components.md", date: null, title: "uniwind className is a silent no-op on third-party components (native only)" },
	{ file: "uniwind-no-group-hover-use-pointer-events.md", date: "2026-07-17", title: "Uniwind has no group / group-hover: — use RN-web pointer events" },
	{ file: "up-next-airing-classification.md", date: "2026-07-23", title: "Up Next: what \"aired\" means per provider (and what it can't mean)" },
	{ file: "vector-icons-web-font-not-loaded.md", date: null, title: "Icons render as tofu on web after @react-native-vector-icons migration" },
	{ file: "watchlist-add-cta-hidden-by-whole-item-membership.md", date: "2026-08-01", title: "\"On your watchlist\" hid the add for every provider still missing the item" },
	{ file: "web-cors-anilist.md", date: "2026-07-07", title: "Web CORS: AniList — GraphQL open, token endpoint blocked → use implicit grant on web" },
	{ file: "web-cors-anizip.md", date: "2026-07-14", title: "Web CORS: ani.zip mappings API — open to browsers, use directly" },
	{ file: "web-cors-letterboxd.md", date: "2026-07-15", title: "Web CORS: Letterboxd (public pages + RSS) — superseded 2026-07-22, reads via Worker proxy" },
	{ file: "web-cors-serializd.md", date: "2026-07-21", title: "Web CORS: Serializd — browser-walled, reached via a same-origin Worker proxy" },
	{ file: "web-cors-simkl.md", date: "2026-07-31", title: "Web CORS: Simkl — fully browser-callable, no proxy" },
	{ file: "web-cors-tmdb.md", date: "2026-07-19", title: "Web CORS: TMDB — fully browser-callable (API + image CDN)" },
	{ file: "web-cors-trakt.md", date: "2026-07-07", title: "Web CORS: Trakt — fully browser-callable (API + OAuth)" },
	{ file: "web-fouc-on-boot.md", date: "2026-07-20", title: "Web boot flash of unstyled content (FOUC)" },
	{ file: "web-headless-smoke-test-playwright.md", date: "2026-07-22", title: "Headless smoke-testing the web build (Playwright)" },
	{ file: "web-mobile-search-autofocus-keyboard-flash.md", date: "2026-07-26", title: "Mobile web: autoFocus on the search field flashes the keyboard open, then closed" },
	{ file: "web-pressto-accessibility-role-kills-onpress.md", date: null, title: "Web: any accessibilityRole other than \"button\" on a pressto pressable silently kills onPress" },
	{ file: "worklets-babel-plugin-version-mismatch.md", date: null, title: "Worklets \"Mismatch between JavaScript code version and Babel plugin version\"" },
];
